name: Hello World

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow
  pull_request:       # This ensures the workflow runs when a pull request is opened or updated

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Step
        run: echo "Hello, World!"